name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: cannoli
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix --option experimental-features "nix-command flakes" flake check -L
